name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Start project server
        run: npm run dev &
      
      - name: Waiting for todo app to start
        run: npx wait-on http://localhost:5173

      - name: Run Cypress tests
        run: npm run test:e2e
